### ISSUE TITLE
help

### ISSUE THREAD

**Issue by kwaknet01** [jsphpl/nds-quota#1]
goodday! i'd like to use your app. done installing required packages, how can i configure all this, upto nodogsplash configuration files. sorry noob here. if you could help me,  i would greatly appreciate it. thanks in advance!

**Comment by jsphpl** [comment]
You basically have to

## 1. Tell nodogsplash to use `preauth.py` as preauth command and make sure it's executable.

On OpenWRT this could done using:
```
uci set nodogsplash.@nodogsplash[0].preauth="/opt/nds-quota/preauth.py"
uci commit
```
Check https://nodogsplashdocs.readthedocs.io/en/stable/preauth.html

## 2. Set up a cron job to check exceeded quota and deauth users

```cron
*/2 * * * * /opt/nds-quota/manage.py update-quota && /opt/nds-quota/manage.py deauth-exceeded
```

## 3. Generate users

```sh
manage.py seed-users
```

Alternatively, you can manually add users to the sqlite database.

**Comment by kwaknet01** [comment]
Thank you so much for the response great app!.
done configure. im using raspbian 

`Nodogsplash version 4.3.4 beta`

make script executable `sudo chmod +x nds-quota/preauth.py`

edit nodogsplash configuration `sudo nano /etc/nodogsplash/nodogsplash.conf`

`GatewayInterface wlan0`

` GatewayAddress 10.3.141.1`

`preauth /PathToWhereFolder-nds-quota/preauth.py`

add crontab job  `sudo contrab -e`
`*/2 * * * * python3 /home/pi/nds-quota/manage.py update-quota && python3 /home/pi/nds-quota/manage.py deauth-exceeded`


it works but there's error. 
url  `http://10.3.141.1:2050/nodogsplash_preauth/?clientip=10.3.141.120&gatewayname=sample&redir=http%3a%2f%2fwww.msftconnecttest.com%2fredirect`
![image](https://user-images.githubusercontent.com/4970710/70304549-228da000-183d-11ea-9ec4-fbb54e81a95d.png)

**Comment by jsphpl** [comment]
Looks like we need to update this to work with recent versions of nodogsplash

**Comment by kwaknet01** [comment]
:) the workaround here is to use the Nodogsplash older version https://github.com/nodogsplash/nodogsplash/releases/tag/v4.2.0 right? 

i'll try it later and send feedback.

**Comment by jsphpl** [comment]
@kwaknet01 4.2.0 is where the change was introduced. So i *assume*, v4.1.0 and below would work.
