### ISSUE TITLE
Handle User Agent string in preauth

### ISSUE THREAD

**Issue by jsphpl** [jsphpl/nds-quota#2]
See https://github.com/nodogsplash/nodogsplash/releases/tag/v4.2.0:
> PreAuth - Send User Agent string to the preauth script [bluewavenet]

This makes preauth.py crash according to #1

**Comment by kwaknet01** [comment]
Nodogsplash 4.1.0 used. https://github.com/nodogsplash/nodogsplash/releases/tag/v4.1.0

Portal works now! 
![2](https://user-images.githubusercontent.com/4970710/70325187-6b108200-186c-11ea-8bad-8bbf0f72b6df.PNG)
![1](https://user-images.githubusercontent.com/4970710/70325188-6b108200-186c-11ea-9800-f50ceebfcc4e.PNG)

New error with preauth.py script at line 65
TypeError: 'NoneType' object is not subscriptable
`self.assign_device_to_user(user, client['mac'])`
`parsed: {'clientip': '10.3.141.82', 'gatewayname': 'samplehotspot', 'password': 'plzdeaij', 'username': 'htdvfuto', 'redir': 'http://www.msftconnecttest.com/redirect'}`

![image](https://user-images.githubusercontent.com/4970710/70325958-44534b00-186e-11ea-9392-ee1373426eba.png)

**Comment by kwaknet01** [comment]
my bad, sorry. so i've check my pythonversion it was python3.5. now I've change it to 3.7. the above error is now ok..

new error now is on
`  File "/home/pi/nds-quota/preauth.py", line 68, in run`
 `   'remaining_quota': self.get_remaining_quota(user, client),`
`  File "/home/pi/nds-quota/preauth.py", line 110, in get_remaining_quota`
 `   return user.max_bytes - used`
`TypeError: unsupported operand type(s) for -: 'int' and 'str'`

![image](https://user-images.githubusercontent.com/4970710/70381927-02212b00-198e-11ea-8490-29575787d768.png)

**Comment by kwaknet01** [comment]
issue solved!~
cheers!

`    def get_remaining_quota(self, user, client):`
`        used = int(client['downloaded'] + client['uploaded']) * 1024`
`        return user.max_bytes - used`

![image](https://user-images.githubusercontent.com/4970710/70382129-7e693d80-1991-11ea-9dbd-0348b6f73a45.png)

![image](https://user-images.githubusercontent.com/4970710/70382147-d9029980-1991-11ea-9fd3-d55ac63914c8.png)
